project:
  title: "Palmer Penguins"
  type: datapage

format:
  datapage-html

execute: 
  echo: false
  message: false
  warning: false
  error: false

redivis:
  user: datapages
  dataset: palmerpenguins
  table: penguins
  # user: mikabr
  # project: irw
  # table: metadata_output
